---
# Source: simple-java-maven-app/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-simple-java-maven-app
  labels:
    helm.sh/chart: simple-java-maven-app-0.1.0
    app.kubernetes.io/name: simple-java-maven-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: simple-java-maven-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-simple-java-maven-app
  labels:
    helm.sh/chart: simple-java-maven-app-0.1.0
    app.kubernetes.io/name: simple-java-maven-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: simple-java-maven-app
    app.kubernetes.io/instance: test
---
# Source: simple-java-maven-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-simple-java-maven-app
  labels:
    helm.sh/chart: simple-java-maven-app-0.1.0
    app.kubernetes.io/name: simple-java-maven-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-java-maven-app
      app.kubernetes.io/instance: test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simple-java-maven-app
        app.kubernetes.io/instance: test
    spec:
      serviceAccountName: test-simple-java-maven-app
      containers:
        - name: simple-java-maven-app
          image: "nginx:1.16.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: MY_CPU_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: java-app
                  resource: requests.cpu
            - name: MY_CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: java-app
                  resource: limits.cpu
            - name: MY_MEM_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: java-app
                  resource: requests.memory
            - name: MY_MEM_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: java-app
                  resource: limits.memory
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            failureThreshold: 1
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 1
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 2
              memory: 1500M
            requests:
              cpu: 1
              memory: 1500M
---
# Source: simple-java-maven-app/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "test-simple-java-maven-app-test-connection"
  labels:
    helm.sh/chart: simple-java-maven-app-0.1.0
    app.kubernetes.io/name: simple-java-maven-app
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['test-simple-java-maven-app:80']
  restartPolicy: Never
