apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-java-maven-app
  labels:
    app: simple-java-maven-app
spec:
  selector:
    matchLabels:
      app: simple-java-maven-app
  template:
    metadata:
      labels:
        app: simple-java-maven-app
      annotations:
        armsPilotAutoEnable: "on"
        armsPilotCreateAppName: "your-app-name"
        ahasPilotAutoEnable: "on"
        ahasAppName: "your-app-name"
        ahasNamespace: "default"
        msePilotAutoEnable: "on"
        msePilotCreateAppName: "your-app-name"
    spec:
      containers:
      - name: java-app
        image: <your-image>
        resources:
          requests:
            cpu: 1
            memory: 1500M
          limits:
            cpu: 2
            memory: 1500M
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 1
          successThreshold: 1
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 1
          successThreshold: 1
        env:
        - name: MY_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: java-app
              resource: requests.cpu
        - name: MY_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: java-app
              resource: limits.cpu
        - name: MY_MEM_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: java-app
              resource: requests.memory
        - name: MY_MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: java-app
              resource: limits.memory
